# settings/production.yaml

application:
  protocol: http
  host: 0.0.0.0
  base_url: "http://0.0.0.0"
  port: 8080

debug: false

secret:
  # 256 bit encryption key https://acte.ltd/utils/randomkeygen
  secret_key: ""
  token_expiration: 15
  # HMAC secret
  hmac_secret: ""

frontend_url: "https://localhost:4173"